apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "open-webui.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
automountServiceAccountToken: true

